<?php

namespace Database\Seeders;

use App\Models\ServiceBriefTemplate;
use Illuminate\Database\Seeder;

/**
 * Seeds version 1 of each service's brief template. Only runs for a slug
 * that has no template rows yet at all — once an admin has edited a
 * template (creating version 2+), this seeder leaves it alone rather than
 * overwriting their work on a repeat run.
 */
class ServiceBriefTemplateSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->templates() as $serviceSlug => $template) {
            if (ServiceBriefTemplate::query()->where('service_slug', $serviceSlug)->exists()) {
                continue;
            }

            ServiceBriefTemplate::create([
                'service_slug' => $serviceSlug,
                'version' => 1,
                'name' => $template['name'],
                'intro_copy' => $template['intro'] ?? null,
                'estimated_minutes' => $template['estimated_minutes'] ?? 5,
                'steps' => $template['steps'],
                'is_active' => true,
                'created_by' => null,
            ]);
        }
    }

    /**
     * @return array<string, array{name: string, intro?: string, estimated_minutes?: int, steps: array<int, array{title: string, fields: array<int, array<string, mixed>>}>}>
     */
    private function templates(): array
    {
        return [
            'social-media-design' => [
                'name' => 'Social Media Design',
                'estimated_minutes' => 4,
                'steps' => [
                    ['title' => 'What you need', 'fields' => [
                        ['key' => 'sm_platforms', 'label' => 'Which platforms are these designs for?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Instagram', 'Facebook', 'LinkedIn', 'X (Twitter)', 'TikTok', 'WhatsApp Status/DP', 'YouTube', 'Pinterest', 'Threads']],
                        ['key' => 'sm_formats', 'label' => 'What formats do you need?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Single feed posts', 'Carousels', 'Stories', 'Reels/TikTok covers', 'YouTube thumbnails', 'Profile banners & DPs', 'Flyers for reposting', 'Ad creatives']],
                        ['key' => 'sm_quantity', 'label' => 'How many designs do you need?', 'type' => 'select', 'required' => true,
                            'options' => ['8 designs – Starter Pack (₦50,000)', '15 designs – Growth Pack (₦85,000)', 'Fewer than 8', 'More than 15 – custom quote', 'Not sure, advise me']],
                        ['key' => 'sm_quantity_custom', 'label' => 'Exactly how many?', 'type' => 'number', 'required' => true, 'min' => 1, 'max' => 200,
                            'condition' => ['field' => 'sm_quantity', 'operator' => 'in', 'value' => ['Fewer than 8', 'More than 15 – custom quote']]],
                        ['key' => 'sm_engagement_type', 'label' => 'Is this a one-off batch or ongoing monthly work?', 'type' => 'select', 'required' => true,
                            'options' => ['One-off batch', 'Monthly retainer', 'Campaign with a fixed end date', 'Not sure yet']],
                        ['key' => 'sm_campaign_dates', 'label' => 'Campaign start and end dates', 'type' => 'text', 'required' => false,
                            'condition' => ['field' => 'sm_engagement_type', 'operator' => 'equals', 'value' => 'Campaign with a fixed end date']],
                    ]],
                    ['title' => 'Purpose and message', 'fields' => [
                        ['key' => 'sm_goal', 'label' => 'What do you want these posts to achieve?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Brand awareness', 'Drive sales / promo', 'Launch a new product', 'Promote an event', 'Educate (tips, how-tos)', 'Announce something', 'Festive / seasonal greetings', 'Build credibility']],
                        ['key' => 'sm_message', 'label' => 'Describe the offer, product or message in your own words.', 'type' => 'textarea', 'required' => true, 'min' => 30,
                            'placeholder' => "e.g. We're running 20% off all human hair bundles for Detty December, 1st-24th."],
                        ['key' => 'sm_copy_status', 'label' => 'Do you have the captions and text written already?', 'type' => 'select', 'required' => true,
                            'options' => ["Yes – I'll supply all the text", 'No – please write it for me', 'Partly – I have some, help with the rest']],
                        ['key' => 'sm_copy_upload', 'label' => 'Paste your text or upload your copy document.', 'type' => 'textarea', 'required' => true,
                            'condition' => ['field' => 'sm_copy_status', 'operator' => 'not_equals', 'value' => 'No – please write it for me']],
                        ['key' => 'sm_language', 'label' => 'What language should the text be in?', 'type' => 'select', 'required' => true,
                            'options' => ['English', 'Nigerian Pidgin', 'Yoruba', 'Igbo', 'Hausa', 'Mix of English and Pidgin', 'Other']],
                        ['key' => 'sm_cta', 'label' => 'Is there a call-to-action?', 'type' => 'text', 'required' => false, 'placeholder' => 'e.g. DM to order · Click the link in bio'],
                    ]],
                    ['title' => 'Look and feel', 'fields' => [
                        ['key' => 'sm_has_brand', 'label' => 'Do you already have brand assets (logo, colours, fonts)?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – full brand guideline', 'Yes – logo and colours only', 'Logo only', 'Nothing yet']],
                        ['key' => 'sm_brand_files', 'label' => 'Upload your logo and any brand files.', 'type' => 'file', 'required' => true,
                            'condition' => ['field' => 'sm_has_brand', 'operator' => 'not_equals', 'value' => 'Nothing yet']],
                        ['key' => 'sm_has_images', 'label' => 'Do you have product photos or images to use?', 'type' => 'select', 'required' => true,
                            'options' => ["Yes – I'll upload them", 'No – use stock images', 'No – I need a photoshoot arranged', 'Mix of both']],
                        ['key' => 'sm_image_files', 'label' => 'Upload your photos.', 'type' => 'file', 'required' => false,
                            'condition' => ['field' => 'sm_has_images', 'operator' => 'in', 'value' => ["Yes – I'll upload them", 'Mix of both']]],
                        ['key' => 'sm_style', 'label' => 'Which style feels closest to your brand?', 'type' => 'select', 'required' => true,
                            'options' => ['Clean & minimal', 'Bold & loud', 'Luxury / premium', 'Playful & youthful', 'Corporate & formal', 'Afrocentric / cultural', 'Editorial & magazine-like', 'Not sure – recommend for me']],
                        ['key' => 'sm_colour_notes', 'label' => 'Are there colours you want used or avoided?', 'type' => 'text', 'required' => false, 'placeholder' => 'Use navy and gold. Please avoid red.'],
                        ['key' => 'sm_references', 'label' => 'Share 2-3 accounts or posts whose look you admire.', 'type' => 'textarea', 'required' => false],
                        ['key' => 'sm_source_files', 'label' => 'Will you need the editable source files?', 'type' => 'radio', 'required' => true,
                            'options' => ['Yes (additional fee applies)', 'No']],
                        ['key' => 'sm_notes', 'label' => 'Anything else we should know?', 'type' => 'textarea', 'required' => false, 'max' => 800],
                    ]],
                ],
            ],

            'graphic-design' => [
                'name' => 'Graphic Design',
                'estimated_minutes' => 4,
                'steps' => [
                    ['title' => "What we're designing", 'fields' => [
                        ['key' => 'gd_item', 'label' => 'What item do you need designed?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Flyer / poster', 'Business card', 'Letterhead & invoice', 'Roll-up banner / backdrop', 'Billboard / outdoor', 'Packaging or product label', 'Menu / price list', 'Brochure or company profile', 'Book cover', 'Certificate', 'Invitation card', 'T-shirt / merchandise', 'Vehicle branding', 'Signage', 'Presentation template', 'Other']],
                        ['key' => 'gd_item_other', 'label' => 'Describe the item.', 'type' => 'text', 'required' => true,
                            'condition' => ['field' => 'gd_item', 'operator' => 'includes', 'value' => 'Other']],
                        ['key' => 'gd_quantity', 'label' => 'How many separate designs in total?', 'type' => 'number', 'required' => true, 'min' => 1, 'max' => 50],
                        ['key' => 'gd_output', 'label' => 'Is this for print, digital, or both?', 'type' => 'select', 'required' => true,
                            'options' => ['Print only', 'Digital only', 'Both']],
                        ['key' => 'gd_size', 'label' => 'What size do you need?', 'type' => 'select', 'required' => true,
                            'options' => ['A4', 'A5', 'A3', 'A6 / handbill', 'Business card (85x55mm)', '2x6ft roll-up banner', '8x4ft banner', 'Custom size', 'Not sure – advise me'],
                            'condition' => ['field' => 'gd_output', 'operator' => 'in', 'value' => ['Print only', 'Both']]],
                        ['key' => 'gd_size_custom', 'label' => 'Enter your custom size (with units).', 'type' => 'text', 'required' => true,
                            'condition' => ['field' => 'gd_size', 'operator' => 'equals', 'value' => 'Custom size']],
                        ['key' => 'gd_print_quote', 'label' => 'Do you also want us to quote the printing?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes, quote printing too', 'No, supply artwork only', 'Not sure'],
                            'condition' => ['field' => 'gd_output', 'operator' => 'in', 'value' => ['Print only', 'Both']]],
                        ['key' => 'gd_print_run', 'label' => 'How many copies would you print?', 'type' => 'select', 'required' => true,
                            'options' => ['Under 100', '100-500', '500-1,000', '1,000-5,000', 'Over 5,000'],
                            'condition' => ['field' => 'gd_print_quote', 'operator' => 'equals', 'value' => 'Yes, quote printing too']],
                    ]],
                    ['title' => 'Content', 'fields' => [
                        ['key' => 'gd_headline', 'label' => 'What is the main message or headline?', 'type' => 'text', 'required' => true, 'max' => 120],
                        ['key' => 'gd_body_copy', 'label' => 'Paste all the text that must appear on the design.', 'type' => 'textarea', 'required' => true, 'min' => 20,
                            'help' => 'Copy it exactly as you want it spelt – names, prices, dates.'],
                        ['key' => 'gd_elements', 'label' => 'Which of these must appear on the design?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Logo', 'Phone number', 'Email address', 'Website URL', 'Social media handles', 'Physical address', 'QR code', 'Price list', 'Map / directions', 'Terms or disclaimer', 'Sponsor or partner logos', 'Barcode']],
                        ['key' => 'gd_has_brand', 'label' => 'Do you have your logo and brand files?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – full guideline', 'Logo and colours only', 'Logo only', 'Nothing yet']],
                        ['key' => 'gd_brand_files', 'label' => 'Upload your brand files.', 'type' => 'file', 'required' => true,
                            'condition' => ['field' => 'gd_has_brand', 'operator' => 'not_equals', 'value' => 'Nothing yet']],
                        ['key' => 'gd_images', 'label' => 'Upload any images you want used.', 'type' => 'file', 'required' => false,
                            'help' => 'Images under 1000px wide may look blurry in print.'],
                    ]],
                    ['title' => 'Style', 'fields' => [
                        ['key' => 'gd_style', 'label' => 'What style are you going for?', 'type' => 'select', 'required' => true,
                            'options' => ['Clean & minimal', 'Bold & loud', 'Luxury / premium', 'Playful & colourful', 'Corporate & formal', 'Afrocentric / cultural', 'Vintage / retro', 'Not sure – recommend']],
                        ['key' => 'gd_colour_notes', 'label' => 'Colours to use or avoid', 'type' => 'text', 'required' => false],
                        ['key' => 'gd_references', 'label' => 'Link any designs you like as reference (one per line).', 'type' => 'textarea', 'required' => false],
                        ['key' => 'gd_source_files', 'label' => 'Will you need the editable source files?', 'type' => 'radio', 'required' => true,
                            'options' => ['Yes (additional fee applies)', 'No']],
                        ['key' => 'gd_notes', 'label' => 'Anything else?', 'type' => 'textarea', 'required' => false, 'max' => 800],
                    ]],
                ],
            ],

            'brand-design' => [
                'name' => 'Brand Design',
                'estimated_minutes' => 10,
                'steps' => [
                    ['title' => 'Scope', 'fields' => [
                        ['key' => 'bd_scope', 'label' => 'What do you need?', 'type' => 'select', 'required' => true,
                            'options' => ['Logo only', 'Logo + basic kit', 'Full identity system', 'Rebrand / refresh', 'Brand guidelines document only', 'Not sure – advise me']],
                        ['key' => 'bd_deliverables', 'label' => 'Which deliverables do you expect?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Logo files (all formats)', 'Colour palette', 'Typography system', 'Business card & letterhead', 'Social media kit', 'Packaging design', 'Signage / storefront', 'Uniform & merchandise', 'Brand guideline PDF', 'Brand voice & messaging', 'Naming', 'Tagline / slogan']],
                        ['key' => 'bd_naming', 'label' => 'Do you need us to create the brand name?', 'type' => 'radio', 'required' => true,
                            'options' => ["Yes – I don't have a name yet", 'No – my name is fixed', "I have a name but I'm open to change"]],
                    ]],
                    ['title' => 'About the brand', 'fields' => [
                        ['key' => 'bd_name', 'label' => 'What is the brand name?', 'type' => 'text', 'required' => true,
                            'condition' => ['field' => 'bd_naming', 'operator' => 'not_equals', 'value' => "Yes – I don't have a name yet"]],
                        ['key' => 'bd_name_meaning', 'label' => 'How is it pronounced, and what does it mean?', 'type' => 'textarea', 'required' => false,
                            'condition' => ['field' => 'bd_naming', 'operator' => 'not_equals', 'value' => "Yes – I don't have a name yet"]],
                        ['key' => 'bd_tagline', 'label' => 'Do you have a tagline?', 'type' => 'text', 'required' => false, 'placeholder' => "Leave blank if you'd like us to write one."],
                        ['key' => 'bd_one_liner', 'label' => 'In one sentence, what does your business do?', 'type' => 'textarea', 'required' => true, 'min' => 15, 'max' => 200],
                        ['key' => 'bd_offerings', 'label' => 'What are your top 3 products or services?', 'type' => 'textarea', 'required' => true, 'help' => 'One per line'],
                        ['key' => 'bd_audience', 'label' => 'Who is your ideal customer?', 'type' => 'textarea', 'required' => true,
                            'placeholder' => 'e.g. Women aged 25-40 in Lagos who run small businesses and shop on Instagram.'],
                        ['key' => 'bd_audience_age', 'label' => 'What age group are they mainly?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Under 18', '18-24', '25-34', '35-44', '45-54', '55+', 'All ages']],
                        ['key' => 'bd_positioning', 'label' => 'What price positioning are you?', 'type' => 'select', 'required' => true,
                            'options' => ['Budget-friendly / mass market', 'Mid-range', 'Premium', 'Luxury', 'Mixed tiers']],
                        ['key' => 'bd_competitors', 'label' => 'Name 2-3 competitors and their handles or websites.', 'type' => 'textarea', 'required' => true],
                        ['key' => 'bd_differentiator', 'label' => 'What makes you genuinely different from them?', 'type' => 'textarea', 'required' => true, 'min' => 20],
                        ['key' => 'bd_vision', 'label' => 'Where do you want this brand to be in 3 years?', 'type' => 'textarea', 'required' => false],
                    ]],
                    ['title' => 'Brand personality', 'fields' => [
                        ['key' => 'bd_scale_modern', 'label' => 'Traditional to Modern', 'type' => 'scale', 'required' => true, 'min' => 1, 'max' => 5],
                        ['key' => 'bd_scale_playful', 'label' => 'Serious to Playful', 'type' => 'scale', 'required' => true, 'min' => 1, 'max' => 5],
                        ['key' => 'bd_scale_premium', 'label' => 'Affordable to Premium', 'type' => 'scale', 'required' => true, 'min' => 1, 'max' => 5],
                        ['key' => 'bd_scale_bold', 'label' => 'Subtle to Bold', 'type' => 'scale', 'required' => true, 'min' => 1, 'max' => 5],
                        ['key' => 'bd_scale_personal', 'label' => 'Corporate to Personal', 'type' => 'scale', 'required' => true, 'min' => 1, 'max' => 5],
                        ['key' => 'bd_adjectives', 'label' => 'Pick up to 5 words that describe how the brand should feel.', 'type' => 'multiselect', 'required' => true, 'max_selections' => 5,
                            'options' => ['Trustworthy', 'Innovative', 'Warm', 'Bold', 'Elegant', 'Affordable', 'Youthful', 'Established', 'Fun', 'Calm', 'Powerful', 'Honest', 'Creative', 'Professional', 'Community-focused', 'Aspirational']],
                    ]],
                    ['title' => 'Visual direction', 'fields' => [
                        ['key' => 'bd_logo_type', 'label' => 'What type of logo do you have in mind?', 'type' => 'select', 'required' => true,
                            'options' => ['Wordmark', 'Lettermark / monogram', 'Icon + text', 'Emblem or badge', 'Mascot / character', 'Not sure – recommend for me']],
                        ['key' => 'bd_logo_usage', 'label' => 'Where will this logo be used?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Social media', 'Website', 'Print documents', 'Signage / shopfront', 'Packaging', 'Vehicle branding', 'Uniforms & embroidery', 'App icon', 'Stamps & seals', 'Billboards']],
                        ['key' => 'bd_colours_want', 'label' => 'Colours you want', 'type' => 'text', 'required' => false],
                        ['key' => 'bd_colours_avoid', 'label' => 'Colours to avoid, and why', 'type' => 'text', 'required' => false],
                        ['key' => 'bd_admired_brands', 'label' => 'Name 3 brands whose identity you admire, and say why.', 'type' => 'textarea', 'required' => true, 'min' => 20],
                        ['key' => 'bd_dislikes', 'label' => "Is there anything you definitely don't want to see?", 'type' => 'textarea', 'required' => false],
                        ['key' => 'bd_existing_files', 'label' => 'Do you have existing brand materials we should look at?', 'type' => 'file', 'required' => false,
                            'condition' => ['field' => 'brand_stage', 'operator' => 'not_equals', 'value' => 'Brand new – not launched yet']],
                        ['key' => 'bd_trademark', 'label' => 'Are you planning to trademark this brand?', 'type' => 'select', 'required' => false,
                            'options' => ['Yes – already in progress', "Yes – I'd like guidance", 'No', 'Not sure']],
                        ['key' => 'bd_launch_date', 'label' => "Is there a launch or event date we're working towards?", 'type' => 'date', 'required' => false],
                        ['key' => 'bd_notes', 'label' => 'Anything else?', 'type' => 'textarea', 'required' => false, 'max' => 1000],
                    ]],
                ],
            ],

            'web-design' => [
                'name' => 'Web Design',
                'estimated_minutes' => 7,
                'steps' => [
                    ['title' => 'The site', 'fields' => [
                        ['key' => 'wd_type', 'label' => 'What kind of website do you need?', 'type' => 'select', 'required' => true,
                            'options' => ['Single landing page', 'Business / corporate website', 'Online store (e-commerce)', 'Portfolio site', 'Blog / magazine', 'Booking or appointment site', 'School, church or NGO site', 'Web app / dashboard', 'Redesign of an existing site']],
                        ['key' => 'wd_existing_url', 'label' => "What's your current website address?", 'type' => 'url', 'required' => true,
                            'condition' => ['field' => 'wd_type', 'operator' => 'equals', 'value' => 'Redesign of an existing site']],
                        ['key' => 'wd_existing_issues', 'label' => 'What do you dislike about the current site?', 'type' => 'textarea', 'required' => true,
                            'condition' => ['field' => 'wd_type', 'operator' => 'equals', 'value' => 'Redesign of an existing site']],
                        ['key' => 'wd_page_count', 'label' => 'Roughly how many pages?', 'type' => 'select', 'required' => true,
                            'options' => ['1 page', '2-5 pages', '6-10 pages', '11-20 pages', 'Over 20 pages', 'Not sure – advise me']],
                        ['key' => 'wd_build_type', 'label' => 'How should it be built?', 'type' => 'select', 'required' => true,
                            'options' => ['No-code (Webflow, Framer, WordPress)', 'Custom-coded (Laravel + React)', 'Not sure – recommend the best fit']],
                        ['key' => 'wd_primary_goal', 'label' => 'What is the main thing you want visitors to do?', 'type' => 'select', 'required' => true,
                            'options' => ['Contact / enquire', 'Buy a product', 'Book an appointment', 'Register or sign up', 'Download something', 'Read and learn', 'Build credibility only']],
                    ]],
                    ['title' => 'Features', 'fields' => [
                        ['key' => 'wd_features', 'label' => 'Which features do you need?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Contact form', 'WhatsApp chat button', 'Live chat', 'Blog / news section', 'Photo or video gallery', 'Online payment', 'Booking calendar', 'User accounts & login', 'Admin dashboard', 'Newsletter signup', 'Google Maps', 'File downloads', 'Multi-language', 'Search', 'Reviews / testimonials', 'Careers / job board']],
                        ['key' => 'wd_gateway', 'label' => 'Which payment gateway do you want?', 'type' => 'select', 'required' => true,
                            'options' => ['Paystack', 'Flutterwave', 'Monnify', 'Stripe', 'PayPal', 'Bank transfer only', 'Not sure – recommend'],
                            'condition' => ['field' => 'wd_features', 'operator' => 'includes', 'value' => 'Online payment']],
                        ['key' => 'wd_product_count', 'label' => 'Roughly how many products will you list?', 'type' => 'select', 'required' => true,
                            'options' => ['Under 20', '20-100', '100-500', 'Over 500', 'Not sure'],
                            'condition' => ['field' => 'wd_type', 'operator' => 'equals', 'value' => 'Online store (e-commerce)']],
                        ['key' => 'wd_legal_pages', 'label' => 'Do you need legal pages (Privacy Policy, Terms, Refund Policy)?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – please prepare them', 'No – I already have them', 'Not sure']],
                    ]],
                    ['title' => 'Content & assets', 'fields' => [
                        ['key' => 'wd_content_source', 'label' => 'Who will provide the website text?', 'type' => 'select', 'required' => true,
                            'options' => ["I'll supply everything", 'Please write it for me', "I'll supply some, you write the rest"]],
                        ['key' => 'wd_image_source', 'label' => 'Who will provide images?', 'type' => 'select', 'required' => true,
                            'options' => ["I'll supply my own", 'Use stock images', 'Mix of both', 'I need a photoshoot arranged']],
                        ['key' => 'wd_content_files', 'label' => 'Upload any content or images you already have.', 'type' => 'file', 'required' => false],
                        ['key' => 'wd_has_brand', 'label' => 'Do you have your logo and brand colours?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – full guideline', 'Logo and colours only', 'Logo only', 'Nothing yet']],
                        ['key' => 'wd_references', 'label' => 'Share 2-3 websites you like and say what you like about them.', 'type' => 'textarea', 'required' => true, 'min' => 20],
                    ]],
                    ['title' => 'Technical & aftercare', 'fields' => [
                        ['key' => 'wd_domain_status', 'label' => 'Do you already own a domain name?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – I own it', 'No – please buy one for me', "I'm not sure"]],
                        ['key' => 'wd_domain_name', 'label' => 'What is the domain name?', 'type' => 'text', 'required' => true,
                            'condition' => ['field' => 'wd_domain_status', 'operator' => 'not_equals', 'value' => "I'm not sure"]],
                        ['key' => 'wd_hosting_status', 'label' => 'Do you have hosting?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – I have hosting', 'No – please arrange it', 'Not sure what that means']],
                        ['key' => 'wd_seo', 'label' => 'Do you want search engine setup (SEO basics + Google Analytics)?', 'type' => 'radio', 'required' => true,
                            'options' => ['Yes', 'No', 'Explain this to me first']],
                        ['key' => 'wd_maintenance', 'label' => 'Who will update the site after launch?', 'type' => 'select', 'required' => true,
                            'options' => ["Me or my staff – we'll need training", 'Bellah Options – quote me a care plan', 'Not decided yet']],
                        ['key' => 'wd_launch_date', 'label' => 'Do you have a launch deadline?', 'type' => 'date', 'required' => false],
                        ['key' => 'wd_notes', 'label' => 'Anything else?', 'type' => 'textarea', 'required' => false, 'max' => 1000],
                    ]],
                ],
            ],

            'special-service' => [
                'name' => 'Special Service',
                'estimated_minutes' => 5,
                'steps' => [
                    ['title' => 'What you need', 'fields' => [
                        ['key' => 'ss_category', 'label' => 'Which of these is closest to what you need?', 'type' => 'select', 'required' => true,
                            'options' => ['Logo animation', 'Motion graphics / explainer video', 'Video editing', 'Pitch deck or presentation design', 'Book cover & interior layout', 'Book publishing support (ISBN, listing)', 'Ad campaign management', 'Photography or shoot direction', 'Print production management', 'Brand strategy consulting session', 'Training or workshop', 'Something else entirely']],
                        ['key' => 'ss_description', 'label' => 'Describe what you need in your own words.', 'type' => 'textarea', 'required' => true, 'min' => 50,
                            'placeholder' => "Tell us what it's for, who will see it, and what success looks like."],
                    ]],
                    ['title' => 'Details', 'fields' => [
                        ['key' => 'ss_anim_duration', 'label' => 'How long should the animation be?', 'type' => 'select', 'required' => true,
                            'options' => ['Under 5 seconds', '5-10 seconds', '10-30 seconds', '30-60 seconds', 'Over 1 minute'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Logo animation', 'Motion graphics / explainer video']]],
                        ['key' => 'ss_anim_style', 'label' => 'What style?', 'type' => 'select', 'required' => true,
                            'options' => ['Simple 2D reveal', '3D animation', 'Liquid / morphing', 'Particle / light effects', 'Character animation', 'Not sure – recommend'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Logo animation', 'Motion graphics / explainer video']]],
                        ['key' => 'ss_anim_vector', 'label' => 'Do you have your logo in vector format (AI, EPS, SVG)?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes', 'No – only PNG/JPG', "I don't have a logo yet"],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Logo animation', 'Motion graphics / explainer video']]],
                        ['key' => 'ss_anim_files', 'label' => 'Upload your logo files.', 'type' => 'file', 'required' => false,
                            'condition' => ['field' => 'ss_anim_vector', 'operator' => 'not_equals', 'value' => "I don't have a logo yet"]],
                        ['key' => 'ss_anim_audio', 'label' => 'Do you need sound design or music?', 'type' => 'radio', 'required' => true,
                            'options' => ['Yes', 'No', 'Not sure'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Logo animation', 'Motion graphics / explainer video']]],
                        ['key' => 'ss_anim_usage', 'label' => 'Where will it be used?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Social media intro', 'Video intro/outro', 'Website header', 'TV / cinema', 'Presentation', 'App splash screen'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Logo animation', 'Motion graphics / explainer video']]],

                        ['key' => 'ss_deck_slides', 'label' => 'Roughly how many slides?', 'type' => 'select', 'required' => true,
                            'options' => ['Under 10', '10-20', '20-35', 'Over 35', 'Not sure'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Pitch deck or presentation design']],
                        ['key' => 'ss_deck_purpose', 'label' => "What's the deck for?", 'type' => 'select', 'required' => true,
                            'options' => ['Investor pitch', 'Sales / client proposal', 'Internal presentation', 'Conference talk', 'Training material', 'Grant application'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Pitch deck or presentation design']],
                        ['key' => 'ss_deck_content', 'label' => 'Is your content written already?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – full script/content ready', 'Rough notes only', 'No – help me structure it'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Pitch deck or presentation design']],
                        ['key' => 'ss_deck_files', 'label' => 'Upload your current deck or content.', 'type' => 'file', 'required' => false,
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Pitch deck or presentation design']],

                        ['key' => 'ss_book_scope', 'label' => 'What do you need?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Front cover only', 'Full cover (front, spine, back)', 'Interior layout / typesetting', 'E-book formatting', 'ISBN registration support', 'Print coordination'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Book cover & interior layout', 'Book publishing support (ISBN, listing)']]],
                        ['key' => 'ss_book_size', 'label' => 'What trim size?', 'type' => 'select', 'required' => true,
                            'options' => ['A5', '5x8 in', '6x9 in', 'A4', 'Custom', 'Not sure'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Book cover & interior layout', 'Book publishing support (ISBN, listing)']]],
                        ['key' => 'ss_book_genre', 'label' => 'What genre?', 'type' => 'select', 'required' => true,
                            'options' => ['Non-fiction / business', 'Christian / devotional', 'Fiction', 'Memoir / biography', 'Academic', "Children's", 'Poetry', 'Other'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Book cover & interior layout', 'Book publishing support (ISBN, listing)']]],
                        ['key' => 'ss_book_manuscript', 'label' => 'Do you have the manuscript ready?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – final', 'Yes – still editing', 'Not yet'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'in', 'value' => ['Book cover & interior layout', 'Book publishing support (ISBN, listing)']]],

                        ['key' => 'ss_ads_platforms', 'label' => 'Which platforms?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Meta (Facebook & Instagram)', 'TikTok', 'Google', 'LinkedIn', 'X (Twitter)'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Ad campaign management']],
                        ['key' => 'ss_ads_goal', 'label' => 'What is the campaign goal?', 'type' => 'select', 'required' => true,
                            'options' => ['Sales / conversions', 'Leads & enquiries', 'Page followers', 'Website traffic', 'App installs', 'Awareness'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Ad campaign management']],
                        ['key' => 'ss_ads_spend', 'label' => 'What monthly ad spend are you planning? (separate from our fee)', 'type' => 'select', 'required' => true,
                            'options' => ['Under ₦50,000', '₦50,000-₦200,000', '₦200,000-₦500,000', '₦500,000-₦1,000,000', 'Over ₦1,000,000', 'Not decided'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Ad campaign management']],
                        ['key' => 'ss_ads_account', 'label' => 'Do you have an existing ad account and pixel installed?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes, both', 'Ad account only', 'Neither', 'Not sure'],
                            'condition' => ['field' => 'ss_category', 'operator' => 'equals', 'value' => 'Ad campaign management']],
                    ]],
                    ['title' => 'Close-out', 'fields' => [
                        ['key' => 'ss_files', 'label' => 'Upload any references, briefs or files.', 'type' => 'file', 'required' => false],
                        ['key' => 'ss_reference_links', 'label' => 'Link to anything similar you like.', 'type' => 'textarea', 'required' => false, 'help' => 'One URL per line'],
                        ['key' => 'ss_engagement', 'label' => 'Is this a one-off or ongoing?', 'type' => 'select', 'required' => true,
                            'options' => ['One-off project', 'Ongoing monthly', 'Retainer over a fixed term', 'Not sure']],
                        ['key' => 'ss_custom_ack', 'label' => 'I understand this is a custom request and pricing will be quoted manually within 48 hours.', 'type' => 'checkbox', 'required' => true],
                    ]],
                ],
            ],

            'mobile-app-development' => [
                'name' => 'Mobile App Development',
                'estimated_minutes' => 8,
                'steps' => [
                    ['title' => 'The app', 'fields' => [
                        ['key' => 'app_platforms', 'label' => 'Which platforms do you need?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Android', 'iOS', 'Web app / PWA', 'Not sure – advise me']],
                        ['key' => 'app_category', 'label' => 'What category best describes the app?', 'type' => 'select', 'required' => true,
                            'options' => ['E-commerce / marketplace', 'Fintech / payments', 'Logistics & delivery', 'Booking & services', 'Social / community', 'Education & learning', 'Health & wellness', 'Church / ministry', 'NGO / social impact', 'Internal business tool', 'Media / streaming', 'Other']],
                        ['key' => 'app_category_other', 'label' => 'Describe it.', 'type' => 'text', 'required' => true,
                            'condition' => ['field' => 'app_category', 'operator' => 'equals', 'value' => 'Other']],
                        ['key' => 'app_summary', 'label' => 'In 2-3 sentences, what does the app do and for whom?', 'type' => 'textarea', 'required' => true, 'min' => 50],
                        ['key' => 'app_stage', 'label' => 'What stage are you at?', 'type' => 'select', 'required' => true,
                            'options' => ['Just an idea', 'I have written requirements', 'I have designs / wireframes', 'I have a working app that needs improving', 'I have an MVP and need version 2']],
                        ['key' => 'app_existing_assets', 'label' => 'Share the link or upload what you have.', 'type' => 'file', 'required' => false,
                            'condition' => ['field' => 'app_stage', 'operator' => 'not_equals', 'value' => 'Just an idea']],
                    ]],
                    ['title' => 'Features', 'fields' => [
                        ['key' => 'app_features', 'label' => 'Which features must the app have?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Sign up & login', 'Social login (Google/Apple)', 'User profiles', 'In-app payments', 'Wallet / balance', 'Chat or messaging', 'Push notifications', 'Maps & live tracking', 'Bookings / scheduling', 'Ratings & reviews', 'Search & filters', 'Admin dashboard', 'Reports & analytics', 'Offline mode', 'Identity verification (KYC/BVN)', 'Referral system', 'Multi-language']],
                        ['key' => 'app_payments', 'label' => 'Will users pay inside the app?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – one-off payments', 'Yes – subscriptions', 'Yes – both', 'No'],
                            'condition' => ['field' => 'app_features', 'operator' => 'includes', 'value' => 'In-app payments']],
                        ['key' => 'app_gateway', 'label' => 'Which payment provider?', 'type' => 'select', 'required' => true,
                            'options' => ['Paystack', 'Flutterwave', 'Monnify', 'Stripe', 'Apple/Google in-app purchase', 'Not sure – recommend'],
                            'condition' => ['field' => 'app_payments', 'operator' => 'not_equals', 'value' => 'No']],
                        ['key' => 'app_compliance_ack', 'label' => 'I understand that wallet, lending and KYC features may require CBN licensing or a licensed partner.', 'type' => 'checkbox', 'required' => true,
                            'condition' => ['field' => 'app_features', 'operator' => 'includes', 'value' => ['Wallet / balance', 'Identity verification (KYC/BVN)']]],
                        ['key' => 'app_backend', 'label' => 'Do you have a backend or API already?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – it exists and is documented', 'Yes – but it needs work', 'No – please build it', 'Not sure']],
                        ['key' => 'app_integrations', 'label' => 'Are there external systems the app must connect to?', 'type' => 'textarea', 'required' => false,
                            'placeholder' => "e.g. our existing inventory system, Google Sheets, a delivery partner's API."],
                    ]],
                    ['title' => 'Design, scale and delivery', 'fields' => [
                        ['key' => 'app_needs_design', 'label' => 'Do you need UI/UX design as part of this?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – design it from scratch', 'No – I have finished designs', 'Partly – I have some screens']],
                        ['key' => 'app_user_scale', 'label' => 'How many users do you expect in the first 6 months?', 'type' => 'select', 'required' => true,
                            'options' => ['Under 500', '500-5,000', '5,000-50,000', 'Over 50,000', 'No idea']],
                        ['key' => 'app_publishing', 'label' => 'Do you need us to publish to the Play Store / App Store?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – handle it fully', "Yes – but I'll own the accounts", "No – I'll publish myself"]],
                        ['key' => 'app_dev_accounts', 'label' => 'Do you already have developer accounts?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes, both', 'Google Play only', 'Apple only', 'Neither – please advise on the fees'],
                            'condition' => ['field' => 'app_publishing', 'operator' => 'not_equals', 'value' => "No – I'll publish myself"]],
                        ['key' => 'app_maintenance', 'label' => 'Do you want a maintenance and support plan after launch?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – monthly plan', 'Yes – on-demand only', 'No', 'Not sure']],
                        ['key' => 'app_nda', 'label' => 'Do you require an NDA before we discuss further?', 'type' => 'radio', 'required' => true,
                            'options' => ['Yes', 'No'], 'flag_on' => ['Yes' => 'nda_required']],
                        ['key' => 'app_notes', 'label' => 'Anything else we should know?', 'type' => 'textarea', 'required' => false, 'max' => 1500],
                    ]],
                ],
            ],

            'ui-ux' => [
                'name' => 'UI/UX',
                'estimated_minutes' => 8,
                'steps' => [
                    ['title' => 'The product', 'fields' => [
                        ['key' => 'ux_product_type', 'label' => 'What are we designing?', 'type' => 'select', 'required' => true,
                            'options' => ['Mobile app', 'Web app / dashboard', 'Website', 'Mobile app + web', 'Design system only', 'Not sure']],
                        ['key' => 'ux_stage', 'label' => 'What stage is the product at?', 'type' => 'select', 'required' => true,
                            'options' => ['Idea / discovery – nothing built yet', 'Requirements written, no designs', 'Designs exist, need improvement', 'Live product needing a redesign', 'Live product with specific problem areas']],
                        ['key' => 'ux_product_link', 'label' => 'Share the link, staging URL or APK.', 'type' => 'url', 'required' => true,
                            'condition' => ['field' => 'ux_stage', 'operator' => 'in', 'value' => ['Live product needing a redesign', 'Live product with specific problem areas']]],
                        ['key' => 'ux_summary', 'label' => 'In 2-3 sentences, what does the product do?', 'type' => 'textarea', 'required' => true, 'min' => 40],
                    ]],
                    ['title' => 'Scope', 'fields' => [
                        ['key' => 'ux_scope', 'label' => 'Which parts of the process do you need?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['User research & interviews', 'Competitor / market audit', 'User personas', 'User flows & journey maps', 'Information architecture', 'Wireframes (low fidelity)', 'High-fidelity UI design', 'Clickable prototype', 'Usability testing', 'Design system / component library', 'Developer handoff & specs', 'Accessibility review']],
                        ['key' => 'ux_screen_count', 'label' => 'Roughly how many screens?', 'type' => 'select', 'required' => true,
                            'options' => ['1-5', '6-15', '16-30', '31-50', 'Over 50', 'Not sure – help me scope it']],
                        ['key' => 'ux_tool', 'label' => 'Which design tool should we work in?', 'type' => 'select', 'required' => true,
                            'options' => ['Figma (our default)', 'Adobe XD', 'Sketch', 'No preference']],
                        ['key' => 'ux_handover', 'label' => 'Do you need the source design files handed over?', 'type' => 'radio', 'required' => true,
                            'options' => ['Yes', 'No']],
                    ]],
                    ['title' => 'Users and problems', 'fields' => [
                        ['key' => 'ux_users', 'label' => 'Who uses this product?', 'type' => 'textarea', 'required' => true,
                            'placeholder' => 'e.g. dispatch riders aged 20-35, mostly on low-end Android phones with patchy data.'],
                        ['key' => 'ux_user_savvy', 'label' => 'How technical are your users?', 'type' => 'select', 'required' => true,
                            'options' => ['Very comfortable with apps', 'Average', 'Not very comfortable', 'Mixed audience']],
                        ['key' => 'ux_devices', 'label' => 'What devices do they mostly use?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['Android phone', 'iPhone', 'Tablet', 'Desktop / laptop', 'Point-of-sale or kiosk']],
                        ['key' => 'ux_core_problem', 'label' => 'What is the single biggest problem you want solved?', 'type' => 'textarea', 'required' => true, 'min' => 30],
                        ['key' => 'ux_complaints', 'label' => 'What do users complain about most?', 'type' => 'textarea', 'required' => false,
                            'placeholder' => "Leave blank if you haven't launched yet."],
                        ['key' => 'ux_has_data', 'label' => 'Do you have any data we can look at (analytics, support tickets, reviews)?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – I can share access', 'Yes – I can export it', 'No', 'Not sure']],
                        ['key' => 'ux_success_metric', 'label' => 'How will you judge whether the design worked?', 'type' => 'multiselect', 'required' => true,
                            'options' => ['More signups', 'More completed purchases', 'Fewer support requests', 'Faster task completion', 'Better app store rating', 'Higher retention', 'Investor / stakeholder approval', 'Not measured yet']],
                    ]],
                    ['title' => 'Working together', 'fields' => [
                        ['key' => 'ux_has_brand', 'label' => 'Do you have brand guidelines we must follow?', 'type' => 'select', 'required' => true,
                            'options' => ['Yes – full guideline', 'Colours and logo only', 'Nothing – design is open', 'Please create the brand too']],
                        ['key' => 'ux_brand_files', 'label' => 'Upload your brand or design files.', 'type' => 'file', 'required' => true,
                            'condition' => ['field' => 'ux_has_brand', 'operator' => 'in', 'value' => ['Yes – full guideline', 'Colours and logo only']]],
                        ['key' => 'ux_dev_team', 'label' => 'Who will build the designs?', 'type' => 'select', 'required' => true,
                            'options' => ['We have an in-house developer', 'We use an external agency', 'No developer – Bellah Options should build it too', 'Not decided']],
                        ['key' => 'ux_accessibility', 'label' => 'Are there accessibility requirements?', 'type' => 'select', 'required' => true,
                            'options' => ['Standard good practice is fine', 'WCAG 2.1 AA compliance required', 'Not sure – advise me']],
                        ['key' => 'ux_references', 'label' => 'Name 2-3 products whose experience you admire.', 'type' => 'textarea', 'required' => true, 'min' => 15],
                        ['key' => 'ux_nda', 'label' => 'Do you require an NDA?', 'type' => 'radio', 'required' => true,
                            'options' => ['Yes', 'No'], 'flag_on' => ['Yes' => 'nda_required']],
                        ['key' => 'ux_notes', 'label' => 'Anything else?', 'type' => 'textarea', 'required' => false, 'max' => 1200],
                    ]],
                ],
            ],
        ];
    }
}
