<?php

return [
    'list' => [
        'Accountant',
        'Accounting Clerk',
        'Actuary',
        'Acupuncturist',
        'Administrative Assistant',
        'Advertising Manager',
        'Aerospace Engineer',
        'Agricultural Engineer',
        'Agricultural Inspector',
        'Agricultural Scientist',
        'Air Traffic Controller',
        'Aircraft Mechanic',
        'Airline Pilot',
        'Ambulance Driver',
        'Anesthesiologist',
        'Animator',
        'Anthropologist',
        'Application Developer',
        'Arbitrator',
        'Archaeologist',
        'Architect',
        'Archivist',
        'Art Director',
        'Assembler',
        'Assistant Professor',
        'Athletic Trainer',
        'Attorney',
        'Audiologist',
        'Auditor',
        'Auto Body Technician',
        'Automotive Mechanic',
        'Baker',
        'Bank Teller',
        'Barber',
        'Bartender',
        'Behavioral Therapist',
        'Biochemist',
        'Biologist',
        'Biomedical Engineer',
        'Biostatistician',
        'Bookkeeper',
        'Brick Mason',
        'Broadcast Technician',
        'Budget Analyst',
        'Bus Driver',
        'Business Analyst',
        'Business Consultant',
        'Business Development Manager',
        'Butcher',
        'Buyer',
        'Cabin Crew',
        'Cardiologist',
        'Caregiver',
        'Carpenter',
        'Cartographer',
        'Cashier',
        'Ceramic Artist',
        'Chef',
        'Chemical Engineer',
        'Chemical Technician',
        'Chemist',
        'Chief Executive Officer',
        'Chief Financial Officer',
        'Chief Operating Officer',
        'Childcare Worker',
        'Chiropractor',
        'Civil Engineer',
        'Claims Adjuster',
        'Clinical Psychologist',
        'Cloud Engineer',
        'Coach',
        'Compliance Officer',
        'Computer Hardware Engineer',
        'Computer Programmer',
        'Construction Laborer',
        'Construction Manager',
        'Content Creator',
        'Content Strategist',
        'Controller',
        'Cook',
        'Copywriter',
        'Correctional Officer',
        'Cosmetologist',
        'Counselor',
        'Court Reporter',
        'Credit Analyst',
        'Criminologist',
        'Customer Support Specialist',
        'Cybersecurity Analyst',
        'Data Analyst',
        'Data Engineer',
        'Data Scientist',
        'Database Administrator',
        'Delivery Driver',
        'Dental Assistant',
        'Dental Hygienist',
        'Dentist',
        'Dermatologist',
        'Designer',
        'Dietitian',
        'Digital Marketing Specialist',
        'Director',
        'Dispatcher',
        'Doctor',
        'Documentation Specialist',
        'Drafter',
        'Drone Operator',
        'Economist',
        'Editor',
        'Education Administrator',
        'Electrical Engineer',
        'Electrician',
        'Electronics Engineer',
        'Elementary School Teacher',
        'Emergency Medical Technician',
        'Energy Consultant',
        'Engineer',
        'English Teacher',
        'Entrepreneur',
        'Environmental Engineer',
        'Environmental Scientist',
        'Epidemiologist',
        'Estimator',
        'Event Coordinator',
        'Executive Assistant',
        'Facilities Manager',
        'Farmer',
        'Fashion Designer',
        'Film Director',
        'Finance Manager',
        'Financial Advisor',
        'Financial Analyst',
        'Firefighter',
        'Flight Dispatcher',
        'Flight Instructor',
        'Florist',
        'Food Scientist',
        'Forensic Scientist',
        'Frontend Developer',
        'Fundraiser',
        'Game Designer',
        'Game Developer',
        'General Manager',
        'Geologist',
        'Graphic Designer',
        'Hair Stylist',
        'Health and Safety Officer',
        'Health Educator',
        'Healthcare Assistant',
        'Human Resources Manager',
        'Human Resources Specialist',
        'Illustrator',
        'Industrial Designer',
        'Industrial Engineer',
        'Information Security Officer',
        'Insurance Agent',
        'Interior Designer',
        'Interpreter',
        'Investment Analyst',
        'Janitor',
        'Jeweler',
        'Judge',
        'Journalist',
        'Kindergarten Teacher',
        'Laboratory Technician',
        'Land Surveyor',
        'Landscape Architect',
        'Law Enforcement Officer',
        'Lawyer',
        'Librarian',
        'Licensed Practical Nurse',
        'Logistics Analyst',
        'Logistics Coordinator',
        'Machine Learning Engineer',
        'Machinist',
        'Maintenance Technician',
        'Management Consultant',
        'Manager',
        'Manufacturing Engineer',
        'Marine Biologist',
        'Market Research Analyst',
        'Marketing Manager',
        'Mason',
        'Massage Therapist',
        'Materials Engineer',
        'Mathematician',
        'Mechanical Engineer',
        'Medical Assistant',
        'Medical Doctor',
        'Medical Laboratory Scientist',
        'Medical Sonographer',
        'Mental Health Counselor',
        'Meteorologist',
        'Microbiologist',
        'Middle School Teacher',
        'Mortgage Advisor',
        'Music Producer',
        'Musician',
        'Nail Technician',
        'Network Administrator',
        'Network Engineer',
        'Neurologist',
        'Nuclear Engineer',
        'Nurse',
        'Nurse Practitioner',
        'Nutritionist',
        'Occupational Therapist',
        'Office Manager',
        'Operations Analyst',
        'Operations Manager',
        'Optician',
        'Optometrist',
        'Orthopedic Surgeon',
        'Painter',
        'Paramedic',
        'Paralegal',
        'Pastor',
        'Pathologist',
        'Pediatrician',
        'Performance Marketer',
        'Personal Assistant',
        'Personal Trainer',
        'Petroleum Engineer',
        'Pharmacist',
        'Pharmacy Technician',
        'Phlebotomist',
        'Photographer',
        'Physical Therapist',
        'Physician',
        'Physician Assistant',
        'Physicist',
        'Plumber',
        'Police Officer',
        'Political Scientist',
        'Postsecondary Teacher',
        'Product Designer',
        'Product Manager',
        'Production Manager',
        'Professor',
        'Project Coordinator',
        'Project Manager',
        'Property Manager',
        'Psychiatrist',
        'Psychologist',
        'Public Health Officer',
        'Public Relations Specialist',
        'Purchasing Manager',
        'Quality Assurance Engineer',
        'Quality Assurance Tester',
        'Radiologic Technologist',
        'Radiologist',
        'Real Estate Agent',
        'Receptionist',
        'Recruiter',
        'Registered Nurse',
        'Research Assistant',
        'Research Scientist',
        'Respiratory Therapist',
        'Restaurant Manager',
        'Retail Manager',
        'Risk Analyst',
        'Robotics Engineer',
        'Safety Officer',
        'Sales Associate',
        'Sales Manager',
        'Sales Representative',
        'School Counselor',
        'School Principal',
        'Scientist',
        'Scrum Master',
        'Security Analyst',
        'Security Guard',
        'Social Media Manager',
        'Social Worker',
        'Sociologist',
        'Software Architect',
        'Software Developer',
        'Software Engineer',
        'Software Tester',
        'Solar Technician',
        'Special Education Teacher',
        'Speech Therapist',
        'Statistician',
        'Stockbroker',
        'Strategist',
        'Structural Engineer',
        'Supply Chain Manager',
        'Surgeon',
        'Surveyor',
        'Systems Administrator',
        'Systems Analyst',
        'Tax Consultant',
        'Teacher',
        'Technical Recruiter',
        'Technical Support Engineer',
        'Technician',
        'Telecommunications Engineer',
        'Therapist',
        'Tool and Die Maker',
        'Tour Guide',
        'Trader',
        'Training Manager',
        'Translator',
        'Transportation Manager',
        'Travel Consultant',
        'Truck Driver',
        'UI Designer',
        'UI Engineer',
        'UX Designer',
        'UX Researcher',
        'Veterinarian',
        'Video Editor',
        'Virtual Assistant',
        'Warehouse Manager',
        'Web Developer',
        'Welder',
        'Writer',
        'Zoologist',
    ],
];
