<?php

return [
    'logo_addons' => [
        'starter' => [
            'name' => 'Starter Logo Package',
            'price' => 65000,
            'description' => 'Logo design, brand style guide, color system, and logo system.',
        ],
        'startup' => [
            'name' => 'Startup Brand Package',
            'price' => 145000,
            'description' => 'Everything in Starter, plus stationery design and mockups.',
        ],
        'big-business' => [
            'name' => 'Big Business Brand Package',
            'price' => 250000,
            'description' => 'Everything in Startup, plus 1 roll-up banner, 150 business cards, 2 lanyards, and 2 ID cards.',
        ],
    ],
    'services' => [
        'social-media-design' => [
            'name' => 'Social Media Design',
            'description' => 'Monthly social design support with content development and revision rounds.',
            'intake' => [
                [
                    'name' => 'primary_platforms',
                    'label' => 'Primary Platforms',
                    'type' => 'text',
                    'required' => true,
                    'max' => 255,
                    'placeholder' => 'Instagram, LinkedIn, Facebook',
                    'hint' => 'List the platforms where designs will be published.',
                ],
            ],
            'packages' => [
                'starter' => [
                    'name' => 'Starter Plan',
                    'price' => 50000,
                    'description' => '8 designs, content development service, and up to 5 iterations.',
                ],
                'standard' => [
                    'name' => 'Standard Plan',
                    'price' => 80000,
                    'description' => '15 designs and everything in Starter Plan.',
                ],
                'business' => [
                    'name' => 'Business Plan',
                    'price' => 140000,
                    'description' => '20 designs and everything in Starter and Standard plans.',
                ],
            ],
        ],
        'graphic-design' => [
            'name' => 'Graphic Design',
            'description' => 'Design support for campaign creatives, print work, and visual assets.',
            'intake' => [
                [
                    'name' => 'design_asset_types',
                    'label' => 'Design Asset Types Needed',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1400,
                    'rows' => 4,
                    'placeholder' => 'Flyers, ad creatives, brochures, social posts...',
                ],
                [
                    'name' => 'usage_channels',
                    'label' => 'Usage Channels',
                    'type' => 'text',
                    'required' => true,
                    'max' => 255,
                    'placeholder' => 'Instagram, print, billboard, website...',
                ],
                [
                    'name' => 'asset_dimensions',
                    'label' => 'Asset Dimensions / Sizes',
                    'type' => 'text',
                    'required' => false,
                    'max' => 255,
                    'placeholder' => '1080x1080, A4, 1920x1080...',
                ],
                [
                    'name' => 'existing_brand_assets',
                    'label' => 'Do You Have Existing Brand Assets?',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'yes' => 'Yes, complete brand kit',
                        'partial' => 'Partially',
                        'no' => 'No, we need support',
                    ],
                ],
                [
                    'name' => 'print_required',
                    'label' => 'Do You Need Print-Ready Files?',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'yes' => 'Yes',
                        'no' => 'No',
                    ],
                ],
                [
                    'name' => 'print_specifications',
                    'label' => 'Print Specifications',
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 1000,
                    'rows' => 3,
                    'placeholder' => 'Bleed, color profile, paper size, printer requirements...',
                ],
            ],
            'packages' => [
                'custom-quote' => [
                    'name' => 'Custom Quote',
                    'price' => 0,
                    'description' => 'Pricing is custom based on design type, quantity, application, and size.',
                ],
            ],
        ],
        'brand-design' => [
            'name' => 'Brand Design',
            'description' => 'Logo systems and complete identity development for ambitious brands.',
            'intake' => [
                [
                    'name' => 'brand_stage',
                    'label' => 'Brand Stage',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'new-brand' => 'New brand',
                        'rebrand' => 'Rebrand',
                        'refresh' => 'Brand refresh',
                    ],
                ],
                [
                    'name' => 'rebrand_background',
                    'label' => 'Rebrand / Refresh Background',
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 1200,
                    'rows' => 3,
                    'placeholder' => 'If rebranding or refreshing, tell us why and which elements (if any) should be kept.',
                ],
                [
                    'name' => 'logo_wording',
                    'label' => 'Exact Logo Wording',
                    'type' => 'text',
                    'required' => true,
                    'max' => 200,
                    'placeholder' => 'Exact wording for the logo, including a strapline if needed.',
                ],
                [
                    'name' => 'brand_entity_type',
                    'label' => 'Who Is This Brand For?',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'individual' => 'Individual',
                        'company' => 'Company',
                        'charity' => 'Charity / Non-profit',
                        'other' => 'Other',
                    ],
                ],
                [
                    'name' => 'industry',
                    'label' => 'Industry / Niche',
                    'type' => 'text',
                    'required' => true,
                    'max' => 160,
                    'placeholder' => 'Fintech, fashion, healthcare...',
                ],
                [
                    'name' => 'brand_story',
                    'label' => 'Your Brand Story',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1600,
                    'rows' => 4,
                    'placeholder' => 'When you started, what you do, and where you see the brand in future. Feel free to include website/social links.',
                ],
                [
                    'name' => 'brand_mission',
                    'label' => 'Mission Statement',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 500,
                    'rows' => 3,
                    'placeholder' => "A short sentence or paragraph on your brand's purpose for being.",
                ],
                [
                    'name' => 'audience_profile',
                    'label' => 'Clients, Customers & Target Audience',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1600,
                    'rows' => 4,
                    'placeholder' => 'Businesses or the public? Size, geography, age, gender, status, interests, and who makes the buying decision.',
                ],
                [
                    'name' => 'key_competitors',
                    'label' => 'Key Competitors',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1200,
                    'rows' => 3,
                    'placeholder' => 'Share competitor names, websites, or social handles so we keep your identity distinct.',
                ],
                [
                    'name' => 'unique_selling_point',
                    'label' => 'Unique Selling Point',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 800,
                    'rows' => 3,
                    'placeholder' => 'What makes your product or service different, and why are you better than your competitors?',
                ],
                [
                    'name' => 'brand_words',
                    'label' => 'Words to Associate With Your Brand',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 800,
                    'rows' => 3,
                    'hint' => 'E.g. Urban, Rural, Natural/Organic, Premium/Luxury, Serious/Hard-hitting, Fun/Light-hearted, Happy/Inspiring, Local, Global, Mature, High-tech, Minimal, Traditional, Modern/Contemporary.',
                    'placeholder' => 'List the words that best describe how you want your brand to appear.',
                ],
                [
                    'name' => 'logo_usage',
                    'label' => 'Where Will the Logo / Identity Be Used?',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 800,
                    'rows' => 3,
                    'hint' => 'E.g. Website, social media, stationery, brochures, exhibitions, shop fronts/signs, uniforms, adverts, merchandising, packaging, vehicles.',
                    'placeholder' => 'List where the identity needs to work, print and/or digital.',
                ],
                [
                    'name' => 'existing_brand_assets',
                    'label' => 'Anything Already In Place?',
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 1000,
                    'rows' => 3,
                    'placeholder' => 'E.g. parent company identity, uniform colours, existing signage format, colour scheme on an existing website.',
                ],
                [
                    'name' => 'visual_references',
                    'label' => 'Visual References',
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 1200,
                    'rows' => 3,
                    'placeholder' => 'Paste your Pinterest board link plus any brands, products, or packaging (with links) that inspire you.',
                ],
                [
                    'name' => 'brand_restrictions',
                    'label' => "Restrictions, Do's and Don'ts",
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 800,
                    'rows' => 3,
                    'placeholder' => 'Content restrictions (e.g. PG-16/NSFW), colours or imagery to use or avoid.',
                ],
                [
                    'name' => 'additional_brand_notes',
                    'label' => 'Anything Else Useful?',
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 1000,
                    'rows' => 3,
                    'placeholder' => 'Any other information that would help us nail your brand identity.',
                ],
            ],
            'packages' => [
                'logo-design' => [
                    'name' => 'Logo Design',
                    'price' => 70000,
                    'description' => 'Distinctive logo concepts and final identity lockups.',
                ],
                'brand-system' => [
                    'name' => 'Brand System Design',
                    'price' => 150000,
                    'description' => 'Typography, color, and layout system documentation.',
                ],
                'full-identity' => [
                    'name' => 'Full Brand Identity',
                    'price' => 280000,
                    'description' => 'Complete strategic and visual identity suite.',
                ],
            ],
        ],
        'web-design' => [
            'name' => 'Web Design',
            'description' => 'Website design and build services tailored by website type and scope.',
            'intake' => [
                [
                    'name' => 'website_type',
                    'label' => 'Website Type',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'landing-page' => 'Landing page',
                        'full-website' => 'Full website',
                        'ecommerce' => 'E-commerce',
                        'custom-web-app' => 'Custom web app',
                    ],
                ],
                [
                    'name' => 'current_website',
                    'label' => 'Current Website (if any)',
                    'type' => 'url',
                    'required' => false,
                    'max' => 255,
                    'placeholder' => 'https://your-site.com',
                ],
                [
                    'name' => 'domain_preference',
                    'label' => 'Preferred Domain Extension',
                    'type' => 'text',
                    'required' => false,
                    'max' => 80,
                    'placeholder' => '.com.ng, .org.ng, .com ...',
                    'hint' => 'Additional fees may apply for non .com.ng or .org.ng domains.',
                ],
                [
                    'name' => 'required_pages',
                    'label' => 'Required Pages / Modules',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1200,
                    'rows' => 3,
                    'placeholder' => 'Home, About, Services, Blog, Contact, portal...',
                ],
                [
                    'name' => 'key_features',
                    'label' => 'Key Features Needed',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1600,
                    'rows' => 4,
                    'placeholder' => 'SEO/LLM, forms, appointment module, CRM, payment, portal...',
                ],
                [
                    'name' => 'content_ready',
                    'label' => 'Is Content Ready?',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'yes' => 'Yes, content is ready',
                        'partial' => 'Partially ready',
                        'no' => 'No, we need guidance',
                    ],
                ],
                [
                    'name' => 'domain_hosting_status',
                    'label' => 'Domain & Hosting Status',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'ready' => 'Already set up',
                        'domain-only' => 'Domain purchased only',
                        'none' => 'Not available yet',
                    ],
                ],
            ],
            'packages' => [
                'landing-page' => [
                    'name' => 'Landing Page',
                    'price' => 120000,
                    'description' => '2 pages plus contact function, SEO/LLM, 1 form, editable content, annual hosting, and domain inclusive.',
                ],
                'full-website' => [
                    'name' => 'Full Website',
                    'price' => 250000,
                    'description' => 'Up to 10 pages, blog module, appointment feature, customer login, CRM, and full social media integration.',
                ],
                'ecommerce' => [
                    'name' => 'E-commerce',
                    'price' => 460000,
                    'description' => 'Everything in Full Website plus payment module (optional), CRM, order management, and order tracking.',
                ],
                'custom-web-app' => [
                    'name' => 'Custom Web App (Consultation)',
                    'price' => 0,
                    'description' => 'Custom web applications go through consultation and scope discovery before final pricing.',
                ],
            ],
        ],
        'special-service' => [
            'name' => 'Special Service',
            'description' => 'Special requests and mixed-scope projects handled through consultation.',
            'intake' => [
                [
                    'name' => 'service_request_type',
                    'label' => 'Special Service Type',
                    'type' => 'text',
                    'required' => true,
                    'max' => 180,
                    'placeholder' => 'Tell us the kind of special request you need.',
                ],
                [
                    'name' => 'special_scope_details',
                    'label' => 'Scope Details',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1600,
                    'rows' => 4,
                    'placeholder' => 'Describe your request, goals, and expected outcome.',
                ],
            ],
            'packages' => [
                'consultation' => [
                    'name' => 'Consultation',
                    'price' => 0,
                    'description' => 'We review your request and provide scope, timeline, and a custom quote.',
                ],
            ],
        ],
        'mobile-app-development' => [
            'name' => 'Mobile App Development',
            'description' => 'Mobile app product development for launch and long-term scale.',
            'intake' => [
                [
                    'name' => 'app_platforms',
                    'label' => 'Target Platforms',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'ios' => 'iOS only',
                        'android' => 'Android only',
                        'both' => 'iOS and Android',
                    ],
                ],
                [
                    'name' => 'app_type',
                    'label' => 'App Type',
                    'type' => 'text',
                    'required' => true,
                    'max' => 180,
                    'placeholder' => 'Marketplace, social app, booking app...',
                ],
                [
                    'name' => 'core_features',
                    'label' => 'Core Features',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1800,
                    'rows' => 4,
                    'placeholder' => 'User auth, chat, payment, notifications, analytics...',
                ],
                [
                    'name' => 'integration_requirements',
                    'label' => '3rd-party Integrations',
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 1400,
                    'rows' => 3,
                    'placeholder' => 'Paystack, Firebase, CRM, maps APIs...',
                ],
                [
                    'name' => 'launch_timeline',
                    'label' => 'Target Launch Timeline',
                    'type' => 'text',
                    'required' => true,
                    'max' => 120,
                    'placeholder' => 'e.g. 10-12 weeks',
                ],
                [
                    'name' => 'existing_product_links',
                    'label' => 'Existing Product Links',
                    'type' => 'textarea',
                    'required' => false,
                    'max' => 700,
                    'rows' => 2,
                    'placeholder' => 'Figma, Notion, prototype links...',
                ],
            ],
            'packages' => [
                'mvp' => [
                    'name' => 'MVP Build',
                    'price' => 900000,
                    'description' => 'Core MVP app build for validated launch.',
                ],
                'growth' => [
                    'name' => 'Growth Build',
                    'price' => 1800000,
                    'description' => 'Feature-rich app with stronger product infrastructure.',
                ],
                'scale' => [
                    'name' => 'Scale Build',
                    'price' => 3200000,
                    'description' => 'High-scale implementation for larger product operations.',
                ],
            ],
        ],
        'ui-ux' => [
            'name' => 'UI/UX Design',
            'description' => 'UX strategy, wireframes, and polished interface systems.',
            'intake' => [
                [
                    'name' => 'product_type',
                    'label' => 'Product Type',
                    'type' => 'text',
                    'required' => true,
                    'max' => 160,
                    'placeholder' => 'SaaS, fintech app, e-commerce, portal...',
                ],
                [
                    'name' => 'ux_stage',
                    'label' => 'Current UX Stage',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'idea' => 'Idea stage',
                        'mvp' => 'MVP in progress',
                        'existing-product' => 'Existing product redesign',
                    ],
                ],
                [
                    'name' => 'user_flows',
                    'label' => 'Priority User Flows',
                    'type' => 'textarea',
                    'required' => true,
                    'max' => 1500,
                    'rows' => 4,
                    'placeholder' => 'Signup, onboarding, checkout, dashboard actions...',
                ],
                [
                    'name' => 'research_available',
                    'label' => 'Do You Have Existing User Research?',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'yes' => 'Yes',
                        'partial' => 'Partially',
                        'no' => 'No',
                    ],
                ],
                [
                    'name' => 'design_system_need',
                    'label' => 'Need a Design System?',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'yes' => 'Yes',
                        'no' => 'No',
                    ],
                ],
                [
                    'name' => 'prototype_fidelity',
                    'label' => 'Preferred Prototype Fidelity',
                    'type' => 'select',
                    'required' => true,
                    'options' => [
                        'low' => 'Low-fidelity wireframes',
                        'mid' => 'Mid-fidelity',
                        'high' => 'High-fidelity interactive',
                    ],
                ],
            ],
            'packages' => [
                'sprint' => [
                    'name' => 'Design Sprint',
                    'price' => 250000,
                    'description' => 'Focused UX/UI sprint for one product flow.',
                ],
                'product' => [
                    'name' => 'Product Design',
                    'price' => 600000,
                    'description' => 'Comprehensive UI/UX package for multi-flow products.',
                ],
                'comprehensive' => [
                    'name' => 'Comprehensive UX System',
                    'price' => 1200000,
                    'description' => 'Deep UX research and full design system handoff.',
                ],
            ],
        ],
        'manage-hires' => [
            'name' => 'Manage Your Hires',
            'description' => 'A monthly retainer with a dedicated Bellah Options design team handling your ongoing design requests.',
            'intake' => [],
            'packages' => [
                'hatchling' => [
                    'name' => 'Hatchling',
                    'price' => 120000,
                    'description' => '20 design requests per month, 1 brand covered, and a dedicated design staff member.',
                    'features' => [
                        '20 design requests per month',
                        '1 brand covered',
                        'Dedicated design staff',
                    ],
                ],
                'business-plan' => [
                    'name' => 'Business Plan',
                    'price' => 240000,
                    'description' => 'Unlimited design requests, 3 brands covered, and a dedicated design staff member.',
                    'features' => [
                        'Unlimited design requests (fair use)',
                        '3 brands covered',
                        'Dedicated design staff',
                    ],
                    'is_recommended' => true,
                ],
            ],
        ],
    ],
];
