<?php

namespace App\Support;

use App\Models\Invoice;

class InvoicePdfBuilder
{
    public function buildInvoice(Invoice $invoice): string
    {
        $lines = [
            config('bellah.invoice.company_name', 'Bellah Options').' - Invoice',
            str_repeat('=', 70),
            'Invoice Number: '.$invoice->invoice_number,
            'Issued At: '.optional($invoice->issued_at)->format('Y-m-d H:i:s'),
            'Due Date: '.($invoice->due_date?->format('Y-m-d') ?? 'N/A'),
            'Status: '.strtoupper($invoice->status),
            '',
            'Billed To',
            'Name: '.$invoice->customer_name,
            'Email: '.$invoice->customer_email,
            'Occupation: '.($invoice->customer_occupation ?: 'N/A'),
            '',
            'Invoice Details',
            'Title: '.$invoice->title,
            ...$this->wrapLine('Description: '.($invoice->description ?: 'N/A')),
            'Amount: '.number_format((float) $invoice->amount, 2).' '.strtoupper($invoice->currency),
            '',
            'Please make payment before the due date and keep this invoice for your records.',
            '',
            'Generated by '.config('bellah.invoice.company_name', 'Bellah Options'),
        ];

        return $this->buildDocument($lines);
    }

    public function buildReceipt(Invoice $invoice): string
    {
        $lines = [
            config('bellah.invoice.company_name', 'Bellah Options').' - Payment Receipt',
            str_repeat('=', 70),
            'Invoice Number: '.$invoice->invoice_number,
            'Receipt Date: '.optional($invoice->paid_at)->format('Y-m-d H:i:s'),
            'Status: PAID',
            '',
            'Customer',
            'Name: '.$invoice->customer_name,
            'Email: '.$invoice->customer_email,
            '',
            'Payment Summary',
            'Description: '.$invoice->title,
            'Amount Paid: '.number_format((float) $invoice->amount, 2).' '.strtoupper($invoice->currency),
            'Payment Reference: '.($invoice->payment_reference ?: 'N/A'),
            '',
            'Thank you for your payment.',
            'Issued by '.config('bellah.invoice.company_name', 'Bellah Options'),
        ];

        return $this->buildDocument($lines);
    }

    /**
     * @param  list<string>  $lines
     */
    private function buildDocument(array $lines): string
    {
        $content = [];
        $lineHeight = 14;
        $y = 790;

        foreach ($lines as $line) {
            if ($y < 40) {
                break;
            }

            $content[] = sprintf(
                "BT\n/F1 11 Tf\n1 0 0 1 40 %d Tm\n(%s) Tj\nET",
                $y,
                $this->escapePdfText($line),
            );

            $y -= $lineHeight;
        }

        $stream = implode("\n", $content);

        $objects = [
            '<< /Type /Catalog /Pages 2 0 R >>',
            '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
            '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
            '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
            '<< /Length '.strlen($stream)." >>\nstream\n{$stream}\nendstream",
        ];

        return $this->renderPdf($objects);
    }

    /**
     * @param  list<string>  $objects
     */
    private function renderPdf(array $objects): string
    {
        $pdf = "%PDF-1.4\n";
        $offsets = [];

        foreach ($objects as $index => $object) {
            $objectNumber = $index + 1;
            $offsets[$objectNumber] = strlen($pdf);
            $pdf .= "{$objectNumber} 0 obj\n{$object}\nendobj\n";
        }

        $xrefOffset = strlen($pdf);
        $size = count($objects) + 1;

        $pdf .= "xref\n0 {$size}\n";
        $pdf .= "0000000000 65535 f \n";

        foreach ($offsets as $offset) {
            $pdf .= sprintf("%010d 00000 n \n", $offset);
        }

        $pdf .= "trailer\n<< /Size {$size} /Root 1 0 R >>\n";
        $pdf .= "startxref\n{$xrefOffset}\n%%EOF";

        return $pdf;
    }

    /**
     * @return list<string>
     */
    private function wrapLine(string $line, int $width = 88): array
    {
        $wrapped = wordwrap($line, $width, "\n", true);

        return explode("\n", $wrapped);
    }

    private function escapePdfText(string $value): string
    {
        $value = preg_replace('/[^\x20-\x7E]/', '?', $value) ?? '';

        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $value);
    }
}
